import { useState } from "react";
import { Copy, Check, ScanLine } from "lucide-react";
import { Button } from "@/components/ui/button";

/**
 * The reference a student shows at the counter.
 *
 * It is the existing `orders.order_number` — `CW-` plus ten uppercase hex characters, generated by
 * create_order_from_cart and already unique. No second identifier is derived: a shortened code
 * would either collide or need new database state, and the brief rules both out.
 *
 * There is deliberately NO QR image and NO scanning. The database has no path that confirms
 * collection separately from completing the order — `transition_order_status` only allows
 * ready_for_pickup → completed, and pickup_status is derived from status rather than set on its
 * own. Rendering a scannable code would imply a verification step that does not exist, so this
 * shows the code to read aloud or show on screen, and says plainly that the vendor confirms.
 *
 * Nothing personal is displayed: the order number identifies an order, not a person, and the vendor
 * already sees it on their own queue.
 */
export function PickupCode({ orderNumber, pickupLocation }: { orderNumber: string; pickupLocation?: string | null }) {
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(orderNumber);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard blocked or unavailable. The code is on screen regardless, which is the point.
    }
  };

  return (
    <div className="rounded-xl border border-border border-l-4 border-l-primary bg-secondary/40 p-4">
      <p className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">
        <ScanLine className="size-3.5" aria-hidden="true" />
        Pickup code
      </p>

      <div className="mt-2 flex flex-wrap items-center gap-3">
        <p className="font-mono text-xl font-extrabold tracking-[0.06em] text-primary">{orderNumber}</p>
        <Button variant="outline" size="sm" onClick={copy} className="min-h-10 gap-1.5" aria-label={`Copy pickup code ${orderNumber}`}>
          {copied ? <Check className="size-3.5" aria-hidden="true" /> : <Copy className="size-3.5" aria-hidden="true" />}
          {copied ? "Copied" : "Copy"}
        </Button>
        {/* Announced politely so a screen reader hears the result without stealing focus. */}
        <span role="status" aria-live="polite" className="sr-only">{copied ? "Pickup code copied" : ""}</span>
      </div>

      <p className="mt-2.5 text-xs leading-5 text-muted-foreground">
        Show this code at {pickupLocation ? <strong className="font-bold text-foreground">{pickupLocation}</strong> : "the collection counter"} when
        you collect your order. The store confirms collection on their side.
      </p>
    </div>
  );
}
