import { useEffect, useRef, useState } from "react";
import { Copy, Check, Download, ScanLine } from "lucide-react";
import { Button } from "@/components/ui/button";
import { drawPickupQr, pickupQrAltText, pickupQrDataUrl, pickupQrFilename } from "@/lib/pickupQr";

/**
 * What a student shows at the counter: the order number, and a QR of that same order number.
 *
 * The code is `orders.order_number` — `CW-` plus ten uppercase hex characters, already unique and
 * already generated by create_order_from_cart. No second identifier is derived, because a shortened
 * one would either collide or need new database state.
 *
 * The QR is drawn on the device from that string alone. It carries no name, no email, no id, no
 * token: it is a lookup key, and the vendor still has to be signed in and still has to staff the
 * owning vendor before the database returns anything.
 *
 * The saved PNG works with no connection — that is the point of downloading it. The copy is careful
 * to promise exactly that and no more: the vendor's verification step still needs the network.
 */
export function PickupCode({ orderNumber, pickupLocation }: { orderNumber: string; pickupLocation?: string | null }) {
  const [copied, setCopied] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (canvasRef.current) drawPickupQr(canvasRef.current, orderNumber);
  }, [orderNumber]);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(orderNumber);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard blocked or unavailable. The code is on screen regardless, which is the point.
    }
  };

  const download = () => {
    try {
      const link = document.createElement("a");
      link.href = pickupQrDataUrl(orderNumber);
      link.download = pickupQrFilename(orderNumber);
      link.click();
    } catch {
      // Nothing to recover: the code is still readable on screen and can be typed by the vendor.
    }
  };

  return (
    <div className="rounded-xl border border-border border-l-4 border-l-primary bg-secondary/40 p-4">
      <p className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">
        <ScanLine className="size-3.5" aria-hidden="true" />
        Pickup code
      </p>

      <div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-start">
        <div className="shrink-0 rounded-xl border border-border bg-white p-2.5">
          {/* Alt text names the order, so the image is meaningful without sight of the code. */}
          <canvas ref={canvasRef} role="img" aria-label={pickupQrAltText(orderNumber)} className="block size-[168px]" />
        </div>

        <div className="min-w-0 flex-1">
          <p className="font-mono text-xl font-extrabold tracking-[0.06em] text-primary">{orderNumber}</p>

          <div className="mt-2.5 flex flex-wrap gap-2">
            <Button variant="outline" size="sm" onClick={copy} className="min-h-11 gap-1.5" aria-label={`Copy pickup code ${orderNumber}`}>
              {copied ? <Check className="size-3.5" aria-hidden="true" /> : <Copy className="size-3.5" aria-hidden="true" />}
              {copied ? "Copied" : "Copy"}
            </Button>
            <Button variant="outline" size="sm" onClick={download} className="min-h-11 gap-1.5" aria-label={`Download pickup QR code for order ${orderNumber}`}>
              <Download className="size-3.5" aria-hidden="true" />
              Download QR
            </Button>
          </div>
          {/* Announced politely so a reader hears the result without focus being stolen. */}
          <span role="status" aria-live="polite" className="sr-only">{copied ? "Pickup code copied" : ""}</span>

          <p className="mt-2.5 text-xs leading-5 text-muted-foreground">
            Show this at {pickupLocation ? <strong className="font-bold text-foreground">{pickupLocation}</strong> : "the collection counter"} when
            you collect. Save the QR before you go — the saved image still opens without internet access.
          </p>
        </div>
      </div>
    </div>
  );
}
