import { useAuth } from "@/_core/hooks/useAuth";
import { BrandMark } from "@/components/campuswear/BrandMark";
import { Button } from "@/components/ui/button";
import { destinationForRole, isVendorApplicationPath, safeNextPath } from "@/lib/authRouting";
import { hasExpiredConfirmationLink } from "@/lib/confirmationGuidance";
import { AlertTriangle, CheckCircle2, Loader2, LogIn, RefreshCw, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function ConfirmedAccount() {
  const [, setLocation] = useLocation();
  const { user, loading } = useAuth();
  const expiredLink = typeof window !== "undefined" && hasExpiredConfirmationLink(window.location.hash);
  const requestedDestination = typeof window !== "undefined" ? safeNextPath(window.location.search) : null;
  const vendorApplicationIntent = isVendorApplicationPath(requestedDestination);
  if (expiredLink) {
    return <main className="grid min-h-screen place-items-center bg-[#eef4fa] px-5 py-10"><section className="w-full max-w-lg rounded-3xl border border-amber-200 bg-card p-7 shadow-sm sm:p-10"><BrandMark /><div className="mt-10 grid size-14 place-items-center rounded-2xl bg-amber-100 text-amber-800"><AlertTriangle className="size-7" aria-hidden="true" /></div><p className="mt-6 text-xs font-bold tracking-[0.12em] text-amber-800">CONFIRMATION LINK EXPIRED</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-0.06em]">Request a fresh confirmation link.</h1><p className="mt-4 text-sm leading-7 text-muted-foreground">For security, confirmation links can expire or become invalid after a newer link is requested. Enter the same email address to send a new link—then check Inbox, Spam/Junk, and Gmail Promotions.</p><Button className="mt-7 h-12 w-full gap-2" onClick={() => setLocation("/auth?mode=confirmation")} >Request new confirmation email <RefreshCw className="size-4" aria-hidden="true" /></Button><Button variant="outline" className="mt-3 h-12 w-full gap-2" onClick={() => setLocation("/auth")}>Back to sign in <LogIn className="size-4" aria-hidden="true" /></Button><Link href="/" className="mt-6 block text-center text-sm font-bold text-primary hover:underline">Back to CampusWear home</Link></section></main>;
  }
  return <main className="grid min-h-screen place-items-center bg-[#eef4fa] px-5 py-10"><section className="w-full max-w-lg rounded-3xl border border-border bg-card p-7 shadow-sm sm:p-10"><BrandMark /><div className="mt-10 grid size-14 place-items-center rounded-2xl bg-[#e7efe6] text-[#3c6248]"><CheckCircle2 className="size-7" /></div><p className="mt-6 text-xs font-bold tracking-[0.12em] text-primary">EMAIL VERIFIED</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-0.06em]">{vendorApplicationIntent ? "Continue your vendor application." : "Your CampusWear account is ready."}</h1><p className="mt-4 text-sm leading-7 text-muted-foreground">{vendorApplicationIntent ? "Your email is verified. Submit your real business and pickup details next; administrator approval is still required before vendor access is activated." : "Thank you for verifying your email. You can now continue securely to the workspace assigned to your account."}</p>{loading ? <div className="mt-7 flex items-center gap-3 rounded-2xl bg-muted px-4 py-3 text-sm font-semibold text-muted-foreground"><Loader2 className="size-4 animate-spin text-primary" />Preparing your account…</div> : user ? <Button className="mt-7 h-12 w-full gap-2" onClick={() => setLocation(requestedDestination ?? destinationForRole(user.role))}>{vendorApplicationIntent ? "Continue application" : "Continue to CampusWear"} <ShieldCheck className="size-4" /></Button> : <><Button className="mt-7 h-12 w-full gap-2" onClick={() => setLocation(requestedDestination ? `/auth?next=${encodeURIComponent(requestedDestination)}` : "/auth")}>Sign in to continue <LogIn className="size-4" /></Button><p className="mt-4 text-center text-xs leading-5 text-muted-foreground">If you confirmed from another browser, sign in here with the password you created.</p></>}<Link href="/" className="mt-6 block text-center text-sm font-bold text-primary hover:underline">Back to CampusWear home</Link></section></main>;
}
